In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
cars_train=pd.read_csv(r'cars_train.csv',header=None)
cars_test=pd.read_csv(r'cars_test.csv',header=None)

In [3]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [4]:
cars_train.shape
cars_train.info()
cars_train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382 entries, 0 to 1381
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1382 non-null   object
 1   maint     1382 non-null   object
 2   doors     1382 non-null   object
 3   persons   1382 non-null   object
 4   lug_boot  1382 non-null   object
 5   safety    1382 non-null   object
 6   classes   1382 non-null   object
dtypes: object(7)
memory usage: 75.7+ KB


buying  maint  doors persons lug_boot safety classes
count    1382   1382   1382    1382     1382   1382    1382
unique      4      4      4       3        3      3       4
top      high  vhigh  5more    more      big   high   unacc
freq      349    352    349     466      467    463     959

In [5]:
cars_test.shape
cars_test.info()
cars_test.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    346 non-null    object
 1   maint     346 non-null    object
 2   doors     346 non-null    object
 3   persons   346 non-null    object
 4   lug_boot  346 non-null    object
 5   safety    346 non-null    object
 6   classes   346 non-null    object
dtypes: object(7)
memory usage: 19.1+ KB


buying maint doors persons lug_boot safety classes
count     346   346   346     346      346    346     346
unique      4     4     4       3        3      3       4
top       low   low     2       2      med    low   unacc
freq       94    94    92     122      122    118     251

In [6]:
cars_train.isnull().sum()


buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [7]:
cars_test.isnull().sum()


buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [8]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [9]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

In [10]:
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder

colname=cars_train.columns
colname

le=LabelEncoder()
 
for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [11]:
# For preprocessing the data
from sklearn.preprocessing import LabelEncoder

colname2=cars_test.columns
colname

le=LabelEncoder()
 
for x in colname2:
    cars_test[x]=le.fit_transform(cars_test[x])

In [12]:
X= cars_train.values[:,0:-1] 
Y= cars_train.values[:,-1]

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [14]:
from sklearn.model_selection import train_test_split
#split the data into test and train 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,random_state=10)

In [15]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# List of models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "KNN Classifier": KNeighborsClassifier(),
    "SVC": SVC(),
    "XGBoost": XGBClassifier(n_estimators=100, random_state=42)
}

# Function to evaluate models
def evaluate_model_performance(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    Y_pred = model.predict(X_test)
    
    # Accuracy
    accuracy = accuracy_score(Y_test, Y_pred)
    print(f"Accuracy: {accuracy:.4f}")
    
    # Classification report (precision, recall, f1-score)
    report = classification_report(Y_test, Y_pred)
    print("Classification Report:\n", report)

# Evaluate each model
for name, model in models.items():
    print(f"Evaluating {name}")
    evaluate_model_performance(model, X_train, X_test, Y_train, Y_test)


Evaluating Logistic Regression
Accuracy: 0.6462
Classification Report:
               precision    recall  f1-score   support

           0       0.30      0.15      0.20        71
           1       0.00      0.00      0.00        12
           2       0.70      0.90      0.79       185
           3       0.33      0.11      0.17         9

    accuracy                           0.65       277
   macro avg       0.33      0.29      0.29       277
weighted avg       0.56      0.65      0.59       277

Evaluating Decision Tree
Accuracy: 0.9783
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98    

# Tuning Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the model
decision_tree = DecisionTreeClassifier(random_state=10)

# Define the parameter grid for hyperparameter tuning
param_grid = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'criterion': ['gini', 'entropy'],  # Common classification criteria
    'splitter': ['best', 'random']
}

# Setup GridSearchCV for classification
grid_search = GridSearchCV(estimator=decision_tree, param_grid=param_grid, 
                           scoring='accuracy', cv=5, verbose=1, n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, Y_train)

# Print the best parameters and best accuracy score
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy Score:", grid_search.best_score_)

# Evaluate on test data
Y_pred = grid_search.best_estimator_.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

# Confusion matrix
conf_matrix = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Classification report (Precision, Recall, F1-score)
class_report = classification_report(Y_test, Y_pred)
print("Classification Report:\n", class_report)


Fitting 5 folds for each of 432 candidates, totalling 2160 fits
Best Parameters: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}
Best Accuracy Score: 0.9004524886877828
Accuracy: 0.9097472924187726
Confusion Matrix:
 [[ 57   5   8   1]
 [  5   7   0   0]
 [  4   0 181   0]
 [  2   0   0   7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.80      0.82        71
           1       0.58      0.58      0.58        12
           2       0.96      0.98      0.97       185
           3       0.88      0.78      0.82         9

    accuracy                           0.91       277
   macro avg       0.81      0.79      0.80       277
weighted avg       0.91      0.91      0.91       277



# evaluating decision tree

In [17]:
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
decision_tree = DecisionTreeClassifier(random_state=10)

# Fit the model on the training data
decision_tree.fit(X_train, Y_train)

# Predict class labels for the test set
y_pred = decision_tree.predict(X_test)

# Print the predicted class labels
print("Predicted Labels:\n", y_pred)

# Predict class probabilities for the test set
y_pred_prob = decision_tree.predict_proba(X_test)

# Print the predicted probabilities for both classes
print("Predicted Probabilities:\n", y_pred_prob)


Predicted Labels:
 [2 2 2 2 2 2 0 2 2 1 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 0 0 2 2 2 0 2
 2 0 2 2 2 2 2 3 0 2 0 3 0 2 0 2 2 2 2 2 2 0 2 0 2 2 0 2 2 0 2 0 0 2 2 0 3
 0 0 2 2 0 2 0 2 2 0 2 2 0 2 2 2 0 2 2 0 2 2 2 2 2 0 3 2 2 0 0 2 2 2 0 2 0
 3 2 0 3 2 2 2 2 2 3 2 0 2 0 2 2 0 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 0 2
 2 2 2 2 0 2 2 0 2 2 2 2 2 2 1 2 2 2 3 1 0 2 2 0 2 2 2 2 2 0 2 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 1 0 2 2 2 2 2 0 0 2 3 1 2 2 0 0 2 0 0
 0 2 2 0 2 2 2 2 0 0 0 2 2 2 0 2 0 2 0 0 0 1 1 2 2 2 0 2 2 2 2 0 1 2 2 2 2
 2 0 2 2 2 2 2 0 2 2 0 0 2 2 1 0 2 2]
Predicted Probabilities:
 [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [18]:

cars_test.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       2      3      3        1         2       1        2
1       3      0      0        0         0       2        2
2       1      0      0        2         2       1        2
3       3      3      1        0         0       0        2
4       1      2      2        1         1       2        1

# PREDICTION

In [19]:
# Drop the 'classes' column from the test data
X_test = cars_test.drop('classes', axis=1)

# Predict class labels for the test set
test_pred = decision_tree.predict(X_test)

# Print the predicted labels
print("Predicted Labels:\n", test_pred)

Predicted Labels:
 [2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2
 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 0 2 2 2 0 0 2
 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 0 2 2 2 2 2 0 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 0 2
 0 0 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 0 2 2 0 2 2 0 2 0 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
